name: Attest Source Controls

on:
  push:
    branches:
      - 'main'

env:
  KOSLI_ORG: kosli-public
  KOSLI_FLOW: test-code-review-action
  KOSLI_API_TOKEN: '${{ secrets.KOSLI_PUBLIC_API_TOKEN }}'

jobs:
  report-pull-request:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Kosli cli
        uses: kosli-dev/setup-cli-action@v2
        with:
          version: ${{ vars.KOSLI_CLI_VERSION }}

      - name: Create Kosli Flow
        run: kosli create flow ${{ env.KOSLI_FLOW }}
          --template-file build-template.yml
          --description "Code Review Demo"

      - name: Begin Kosli Trail
        run: kosli begin trail "${{ github.sha }}"
          --flow ${{ env.KOSLI_FLOW }}

      - name: Attest pull-request evidence to Kosli
        run: kosli attest pullrequest github
          --name pull-request
          --flow ${{ env.KOSLI_FLOW }}
          --trail ${{ github.sha }}
          --github-token ${{ secrets.GITHUB_TOKEN }}


  # pull-request:
  #   needs: [setup]
  #   runs-on: ubuntu-24.04
  #   permissions:
  #     id-token: write
  #     contents: write
  #     pull-requests: read

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #         fetch-tags: true

  #     - name: Setup Kosli cli
  #       uses: kosli-dev/setup-cli-action@v2
  #       with:
  #         version: ${{ vars.KOSLI_CLI_VERSION }}

  #     - name: Attest pull-request evidence to Kosli
  #       run: kosli attest pullrequest github
  #         --name pull-request
  #         --flow ${{ env.KOSLI_FLOW }}
  #         --trail ${{ github.sha }}
  #         --github-token ${{ secrets.GITHUB_TOKEN }}

      
  # code-review:
  #   needs: [pull-request]
  #   runs-on: ubuntu-24.04
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #         fetch-tags: true

  #     - name: Code Review
  #       uses: kosli-dev/control-actions/.github/actions/code-review@main
  #       with:
  #         base_ref: '1.0.0'
  #         kosli_api_token: ${{ secrets.KOSLI_PUBLIC_API_TOKEN }}
  #         kosli_org: 'kosli-public'
  #         kosli_search_flow_name: 'test-code-review-action'
  #         kosli_code_review_attestation_type: 'code-review'
  #         kosli_code_review_attestation_name: 'code-review'
  #         kosli_code_review_flow_name: 'test-code-review-action'
  #         kosli_code_review_trail_name: ${{ github.sha }}
